"""Catalogue complet stock restaurant - Structure par 9 categories principales avec sous-categories"""

CATEGORIES = [
    {"name": "Cuisine", "color": "#ef4444", "description": "Cereales, legumes, viandes, poissons, epices", "subcategories": ["Cereales et feculents","Legumes","Fruits","Viandes","Volailles","Poissons et fruits de mer","Produits laitiers","Huiles et matieres grasses","Epices et condiments","Produits locaux","Legumineuses"]},
    {"name": "Petit-dejeuner", "color": "#f59e0b", "description": "Cafe, the, pain, confiture, cereales", "subcategories": ["Boissons chaudes","Pain et viennoiseries","Accompagnements"]},
    {"name": "Bar et boissons", "color": "#3b82f6", "description": "Eau, sodas, jus, alcools, cocktails", "subcategories": ["Boissons non alcoolisees","Boissons alcoolisees","Cocktails"]},
    {"name": "Grillades", "color": "#f97316", "description": "Viandes, poissons, epices pour grillades", "subcategories": ["Viandes grillade","Accompagnements grillade","Combustibles"]},
    {"name": "Emballages et service", "color": "#8b5cf6", "description": "Barquettes, gobelets, serviettes, emballages", "subcategories": ["Emballages","Vaisselle jetable","Consommables service"]},
    {"name": "Entretien et hygiene", "color": "#06b6d4", "description": "Detergents, desinfectants, nettoyage", "subcategories": ["Produits nettoyage","Materiel nettoyage","Hygiene"]},
    {"name": "Consommables administratifs", "color": "#64748b", "description": "Fiches, cahiers, stylos, imprimante", "subcategories": ["Papeterie","Impression"]},
    {"name": "Evenements et service traiteur", "color": "#ec4899", "description": "Nappes, decorations, materiel evenementiel", "subcategories": ["Decorations","Vaisselle evenementielle","Materiel service"]},
    {"name": "Espace jeux", "color": "#10b981", "description": "Jetons, bracelets, piles, nettoyage jeux", "subcategories": ["Acces et tickets","Electricite","Entretien jeux"]},
]

SUPPLIERS = [
    {"name": "Marche local Dantokpa", "phone": "+229 97 00 11 22", "product_types": "Legumes, condiments, cereales, viandes", "address": "Cotonou"},
    {"name": "Fournisseur boissons", "phone": "+229 97 33 44 55", "product_types": "Sodas, eau, jus, bieres", "address": "Cotonou"},
    {"name": "Fournisseur surgeles", "phone": "+229 97 66 77 88", "product_types": "Viandes, poissons congeles", "address": "Cotonou"},
    {"name": "Fournisseur emballages", "phone": "+229 96 12 34 56", "product_types": "Barquettes, sachets, gobelets", "address": "Cotonou"},
    {"name": "Fournisseur entretien", "phone": "+229 97 99 00 11", "product_types": "Detergents, desinfectants", "address": "Cotonou"},
    {"name": "Fournisseur epicerie generale", "phone": "+229 95 45 67 89", "product_types": "Epicerie, conserves, huiles", "address": "Cotonou"},
    {"name": "Fournisseur bar", "phone": "+229 96 78 90 12", "product_types": "Vins, spiritueux, sirops", "address": "Cotonou"},
    {"name": "Fournisseur jeux et consommables", "phone": "+229 95 11 22 33", "product_types": "Piles, bracelets, tickets", "address": "Cotonou"},
]

# (cat_idx, sub_cat, code_prefix, name, unit, stock_min, stock_max, price, location)
PRODUCTS = [
    # ===== 0: CUISINE =====
    # Cereales et feculents
    (0,"Cereales et feculents","CU","Riz blanc","kg",25,100,500,"Reserve"),
    (0,"Cereales et feculents","CU","Riz parfume","kg",10,50,800,"Reserve"),
    (0,"Cereales et feculents","CU","Spaghetti","paquet",10,60,500,"Reserve"),
    (0,"Cereales et feculents","CU","Macaroni","paquet",10,60,500,"Reserve"),
    (0,"Cereales et feculents","CU","Couscous","kg",5,30,600,"Reserve"),
    (0,"Cereales et feculents","CU","Semoule","kg",5,30,700,"Reserve"),
    (0,"Cereales et feculents","CU","Farine de ble","kg",10,50,400,"Reserve"),
    (0,"Cereales et feculents","CU","Farine de mais","kg",8,40,300,"Reserve"),
    (0,"Cereales et feculents","CU","Farine de manioc","kg",8,40,250,"Reserve"),
    (0,"Cereales et feculents","CU","Gari","kg",5,30,300,"Reserve"),
    (0,"Cereales et feculents","CU","Pomme de terre","kg",15,60,800,"Cuisine"),
    (0,"Cereales et feculents","CU","Patate douce","kg",10,40,500,"Cuisine"),
    (0,"Cereales et feculents","CU","Igname","kg",10,50,600,"Cuisine"),
    (0,"Cereales et feculents","CU","Manioc","kg",10,40,300,"Cuisine"),
    (0,"Cereales et feculents","CU","Banane plantain","regime",3,15,2000,"Cuisine"),
    # Legumes
    (0,"Legumes","CU","Tomate fraiche","kg",10,50,800,"Cuisine"),
    (0,"Legumes","CU","Concentre de tomate","boite",12,60,500,"Reserve"),
    (0,"Legumes","CU","Oignon blanc","kg",10,50,600,"Cuisine"),
    (0,"Legumes","CU","Oignon rouge","kg",10,50,700,"Cuisine"),
    (0,"Legumes","CU","Ail","kg",3,15,3000,"Cuisine"),
    (0,"Legumes","CU","Gingembre","kg",3,15,2000,"Cuisine"),
    (0,"Legumes","CU","Piment frais","kg",3,15,1500,"Cuisine"),
    (0,"Legumes","CU","Piment sec","kg",2,10,3000,"Reserve"),
    (0,"Legumes","CU","Poivron vert","kg",3,15,1500,"Cuisine"),
    (0,"Legumes","CU","Carotte","kg",5,25,500,"Cuisine"),
    (0,"Legumes","CU","Chou","piece",5,20,500,"Cuisine"),
    (0,"Legumes","CU","Laitue","piece",5,20,300,"Cuisine"),
    (0,"Legumes","CU","Concombre","piece",5,20,200,"Cuisine"),
    (0,"Legumes","CU","Gombo","kg",4,20,1200,"Cuisine"),
    (0,"Legumes","CU","Epinards","botte",5,20,200,"Cuisine"),
    (0,"Legumes","CU","Persil","botte",4,15,100,"Cuisine"),
    (0,"Legumes","CU","Celeri","botte",4,15,200,"Cuisine"),
    (0,"Legumes","CU","Citron","kg",4,20,1000,"Cuisine"),
    (0,"Legumes","CU","Avocat","piece",6,25,300,"Cuisine"),
    # Legumineuses
    (0,"Legumineuses","CU","Haricot rouge","kg",5,30,1000,"Reserve"),
    (0,"Legumineuses","CU","Haricot blanc","kg",5,30,800,"Reserve"),
    (0,"Legumineuses","CU","Niebe","kg",5,30,700,"Reserve"),
    (0,"Legumineuses","CU","Arachides","kg",5,25,1000,"Reserve"),
    # Viandes
    (0,"Viandes","CU","Boeuf sans os","kg",10,50,4000,"Chambre froide"),
    (0,"Viandes","CU","Filet de boeuf","kg",5,25,6000,"Chambre froide"),
    (0,"Viandes","CU","Viande hachee","kg",5,25,3500,"Chambre froide"),
    (0,"Viandes","CU","Mouton","kg",5,25,4000,"Chambre froide"),
    (0,"Viandes","CU","Chevre","kg",5,25,3500,"Chambre froide"),
    (0,"Viandes","CU","Porc","kg",5,25,2800,"Chambre froide"),
    # Volailles
    (0,"Volailles","CU","Poulet entier","piece",10,50,2500,"Chambre froide"),
    (0,"Volailles","CU","Poulet bicyclette","piece",8,30,3500,"Chambre froide"),
    (0,"Volailles","CU","Cuisses de poulet","kg",5,25,2800,"Chambre froide"),
    (0,"Volailles","CU","Ailes de poulet","kg",5,25,2000,"Chambre froide"),
    (0,"Volailles","CU","Gesiers","kg",3,15,2000,"Chambre froide"),
    (0,"Volailles","CU","Pintade","piece",4,20,4000,"Chambre froide"),
    # Poissons
    (0,"Poissons et fruits de mer","CU","Poisson frais","kg",8,40,2500,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Poisson congele","kg",8,40,2000,"Congelateur"),
    (0,"Poissons et fruits de mer","CU","Tilapia","kg",5,25,2500,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Bar","kg",4,20,4000,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Capitaine","kg",4,20,4500,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Maquereau","kg",5,25,1500,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Sardine","kg",4,20,1200,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Crevettes","kg",4,20,8000,"Congelateur"),
    (0,"Poissons et fruits de mer","CU","Crabe","kg",2,10,5000,"Chambre froide"),
    (0,"Poissons et fruits de mer","CU","Poisson fume","kg",4,20,4000,"Reserve"),
    (0,"Poissons et fruits de mer","CU","Crevette sechee","kg",2,10,5000,"Reserve"),
    # Produits laitiers
    (0,"Produits laitiers","CU","Lait entier","litre",6,30,800,"Refrigerateur"),
    (0,"Produits laitiers","CU","Lait en poudre","boite",6,30,3000,"Reserve"),
    (0,"Produits laitiers","CU","Beurre","kg",3,15,3000,"Refrigerateur"),
    (0,"Produits laitiers","CU","Margarine","kg",3,15,1000,"Refrigerateur"),
    (0,"Produits laitiers","CU","Creme fraiche","litre",3,15,1500,"Refrigerateur"),
    (0,"Produits laitiers","CU","Fromage fondu","boite",4,20,800,"Refrigerateur"),
    (0,"Produits laitiers","CU","Fromage rape","kg",2,10,2500,"Refrigerateur"),
    (0,"Produits laitiers","CU","Oeufs de poule","plateau",5,25,2000,"Cuisine"),
    # Huiles
    (0,"Huiles et matieres grasses","CU","Huile vegetale","litre",10,50,1200,"Reserve"),
    (0,"Huiles et matieres grasses","CU","Huile de palme","litre",8,40,800,"Reserve"),
    (0,"Huiles et matieres grasses","CU","Huile d'arachide","litre",6,30,1500,"Reserve"),
    # Epices et condiments
    (0,"Epices et condiments","CU","Sel fin","kg",5,30,300,"Cuisine"),
    (0,"Epices et condiments","CU","Poivre noir","sachet",5,30,500,"Cuisine"),
    (0,"Epices et condiments","CU","Cube d'assaisonnement","carton",2,15,5000,"Cuisine"),
    (0,"Epices et condiments","CU","Bouillon en poudre","sachet",6,30,300,"Cuisine"),
    (0,"Epices et condiments","CU","Curry","sachet",4,20,400,"Cuisine"),
    (0,"Epices et condiments","CU","Curcuma","sachet",3,15,500,"Cuisine"),
    (0,"Epices et condiments","CU","Paprika","sachet",3,15,500,"Cuisine"),
    (0,"Epices et condiments","CU","Piment en poudre","sachet",4,20,600,"Cuisine"),
    (0,"Epices et condiments","CU","Thym","sachet",3,15,300,"Cuisine"),
    (0,"Epices et condiments","CU","Moutarde","pot",4,20,800,"Refrigerateur"),
    (0,"Epices et condiments","CU","Mayonnaise","pot",5,25,1500,"Refrigerateur"),
    (0,"Epices et condiments","CU","Ketchup","bouteille",5,25,1000,"Reserve"),
    (0,"Epices et condiments","CU","Vinaigre","bouteille",4,20,600,"Reserve"),
    (0,"Epices et condiments","CU","Sauce soja","bouteille",3,15,1500,"Reserve"),
    (0,"Epices et condiments","CU","Sauce piment","bouteille",4,20,800,"Reserve"),
    (0,"Epices et condiments","CU","Pate d'arachide","kg",4,20,1000,"Reserve"),
    (0,"Epices et condiments","CU","Pate de tomate","boite",8,40,300,"Reserve"),
    # ===== 1: PETIT-DEJEUNER =====
    (1,"Boissons chaudes","PD","Cafe","kg",3,15,5000,"Reserve"),
    (1,"Boissons chaudes","PD","The","boite",4,20,1500,"Reserve"),
    (1,"Boissons chaudes","PD","Chocolat en poudre","boite",3,15,2500,"Reserve"),
    (1,"Boissons chaudes","PD","Lait","litre",6,30,800,"Refrigerateur"),
    (1,"Pain et viennoiseries","PD","Pain baguette","piece",20,100,200,"Cuisine"),
    (1,"Pain et viennoiseries","PD","Pain de mie","paquet",5,25,1000,"Cuisine"),
    (1,"Pain et viennoiseries","PD","Croissant","piece",15,60,300,"Cuisine"),
    (1,"Pain et viennoiseries","PD","Biscottes","paquet",4,20,800,"Reserve"),
    (1,"Accompagnements","PD","Beurre","kg",2,10,3000,"Refrigerateur"),
    (1,"Accompagnements","PD","Confiture","pot",4,20,1200,"Reserve"),
    (1,"Accompagnements","PD","Miel","bouteille",3,15,3000,"Reserve"),
    (1,"Accompagnements","PD","Oeufs","plateau",4,20,2000,"Cuisine"),
    (1,"Accompagnements","PD","Fromage","paquet",4,20,1500,"Refrigerateur"),
    (1,"Accompagnements","PD","Jus d'orange","carton",4,20,3000,"Bar"),
    (1,"Accompagnements","PD","Jus d'ananas","carton",4,20,3000,"Bar"),
    (1,"Accompagnements","PD","Sucre blanc","kg",8,40,800,"Reserve"),
    (1,"Accompagnements","PD","Sucre roux","kg",4,20,1200,"Reserve"),
    # ===== 2: BAR ET BOISSONS =====
    (2,"Boissons non alcoolisees","BA","Eau minerale","carton",10,50,3000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Eau gazeuse","carton",5,25,3500,"Bar"),
    (2,"Boissons non alcoolisees","BA","Soda cola","casier",8,40,6000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Soda orange","casier",5,25,6000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Soda citron","casier",5,25,6000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Soda tonic","casier",4,20,6000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Jus de mangue","carton",4,20,3000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Jus multifruits","carton",4,20,3000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Sirop","bouteille",4,20,2000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Boisson energisante","carton",3,15,8000,"Bar"),
    (2,"Boissons non alcoolisees","BA","Boisson maltee","carton",3,15,4000,"Bar"),
    (2,"Boissons alcoolisees","BA","Biere locale","casier",10,50,7500,"Bar"),
    (2,"Boissons alcoolisees","BA","Biere importee","carton",5,25,12000,"Bar"),
    (2,"Boissons alcoolisees","BA","Vin rouge","bouteille",6,30,5000,"Bar"),
    (2,"Boissons alcoolisees","BA","Vin blanc","bouteille",4,20,5000,"Bar"),
    (2,"Boissons alcoolisees","BA","Vin rose","bouteille",4,20,5000,"Bar"),
    (2,"Boissons alcoolisees","BA","Champagne","bouteille",3,15,25000,"Bar"),
    (2,"Boissons alcoolisees","BA","Whisky","bouteille",4,20,15000,"Bar"),
    (2,"Boissons alcoolisees","BA","Vodka","bouteille",3,15,10000,"Bar"),
    (2,"Boissons alcoolisees","BA","Gin","bouteille",3,15,10000,"Bar"),
    (2,"Boissons alcoolisees","BA","Rhum","bouteille",3,15,8000,"Bar"),
    (2,"Boissons alcoolisees","BA","Liqueurs","bouteille",3,15,8000,"Bar"),
    (2,"Cocktails","BA","Citrons","kg",4,20,1000,"Bar"),
    (2,"Cocktails","BA","Menthe fraiche","botte",4,15,200,"Bar"),
    (2,"Cocktails","BA","Sucre de canne","kg",3,15,1500,"Bar"),
    (2,"Cocktails","BA","Sirop de grenadine","bouteille",3,15,2000,"Bar"),
    (2,"Cocktails","BA","Sirop de menthe","bouteille",3,15,2000,"Bar"),
    (2,"Cocktails","BA","Tonic","carton",3,15,6000,"Bar"),
    (2,"Cocktails","BA","Glacons","sachet",10,50,500,"Congelateur"),
    (2,"Cocktails","BA","Glace pilee","sachet",8,40,1000,"Congelateur"),
    (2,"Cocktails","BA","Bitter","bouteille",2,10,5000,"Bar"),
    (2,"Cocktails","BA","Triple sec","bouteille",2,10,8000,"Bar"),
    (2,"Cocktails","BA","Vermouth","bouteille",2,10,6000,"Bar"),
    # ===== 3: GRILLADES =====
    (3,"Viandes grillade","GR","Poulet entier grillade","piece",10,50,2500,"Chambre froide"),
    (3,"Viandes grillade","GR","Poulet bicyclette grillade","piece",8,30,3500,"Chambre froide"),
    (3,"Viandes grillade","GR","Pintade grillade","piece",4,20,4000,"Chambre froide"),
    (3,"Viandes grillade","GR","Cotelettes de porc","kg",4,20,3200,"Chambre froide"),
    (3,"Viandes grillade","GR","Brochettes de boeuf","kg",4,20,4500,"Chambre froide"),
    (3,"Viandes grillade","GR","Saucisses","kg",4,20,2500,"Chambre froide"),
    (3,"Viandes grillade","GR","Poisson braisable","kg",5,25,2500,"Chambre froide"),
    (3,"Accompagnements grillade","GR","Oignons grillade","kg",5,25,600,"Cuisine"),
    (3,"Accompagnements grillade","GR","Tomates grillade","kg",5,25,800,"Cuisine"),
    (3,"Accompagnements grillade","GR","Piment grillade","kg",2,10,1500,"Cuisine"),
    (3,"Accompagnements grillade","GR","Epices grillades","sachet",3,15,1000,"Cuisine"),
    (3,"Combustibles","GR","Charbon","sac",4,20,3000,"Technique"),
    (3,"Combustibles","GR","Bois de cuisson","fagot",4,20,1500,"Technique"),
    (3,"Combustibles","GR","Allume-feu","boite",3,15,500,"Technique"),
    # ===== 4: EMBALLAGES ET SERVICE =====
    (4,"Emballages","ES","Barquettes alimentaires","paquet",10,50,2000,"Reserve B"),
    (4,"Emballages","ES","Boites repas","paquet",10,50,2500,"Reserve B"),
    (4,"Emballages","ES","Sachets plastiques","paquet",8,40,500,"Reserve B"),
    (4,"Emballages","ES","Sachets kraft","paquet",8,40,800,"Reserve B"),
    (4,"Emballages","ES","Papier aluminium","rouleau",5,25,1500,"Cuisine"),
    (4,"Emballages","ES","Film alimentaire","rouleau",5,25,1200,"Cuisine"),
    (4,"Emballages","ES","Papier cuisson","rouleau",4,20,1000,"Cuisine"),
    (4,"Vaisselle jetable","ES","Papier serviette","paquet",10,50,300,"Salle"),
    (4,"Vaisselle jetable","ES","Serviettes de table","paquet",10,50,500,"Salle"),
    (4,"Vaisselle jetable","ES","Serviettes jetables","paquet",8,40,300,"Salle"),
    (4,"Vaisselle jetable","ES","Gobelets jetables","paquet",8,40,500,"Bar"),
    (4,"Vaisselle jetable","ES","Gobelets plastiques","paquet",8,40,800,"Bar"),
    (4,"Vaisselle jetable","ES","Verres jetables","paquet",6,30,600,"Bar"),
    (4,"Vaisselle jetable","ES","Assiettes jetables","paquet",6,30,1000,"Reserve B"),
    (4,"Vaisselle jetable","ES","Couverts jetables","paquet",6,30,600,"Reserve B"),
    (4,"Consommables service","ES","Pailles","paquet",5,25,300,"Bar"),
    (4,"Consommables service","ES","Cure-dents","boite",3,15,200,"Salle"),
    (4,"Consommables service","ES","Sacs de livraison","paquet",6,30,1500,"Reserve B"),
    (4,"Consommables service","ES","Pots a sauce","paquet",5,25,500,"Reserve B"),
    (4,"Consommables service","ES","Couvercles","paquet",5,25,400,"Reserve B"),
    (4,"Consommables service","ES","Rouleaux ticket caisse","rouleau",4,20,800,"Caisse"),
    # ===== 5: ENTRETIEN ET HYGIENE =====
    (5,"Produits nettoyage","EH","Detergent","bidon",3,15,3500,"Menage"),
    (5,"Produits nettoyage","EH","Eau de javel","bidon",3,15,1500,"Menage"),
    (5,"Produits nettoyage","EH","Savon liquide","bidon",3,15,2000,"Menage"),
    (5,"Produits nettoyage","EH","Liquide vaisselle","bidon",3,15,2500,"Cuisine"),
    (5,"Produits nettoyage","EH","Desinfectant","bidon",3,15,3000,"Menage"),
    (5,"Produits nettoyage","EH","Nettoyant sol","bidon",3,15,2000,"Menage"),
    (5,"Produits nettoyage","EH","Nettoyant vitre","bouteille",3,15,1500,"Menage"),
    (5,"Produits nettoyage","EH","Degraissant","bidon",3,15,2500,"Cuisine"),
    (5,"Produits nettoyage","EH","Desodorisant","aerosol",3,15,1500,"Menage"),
    (5,"Materiel nettoyage","EH","Eponge","paquet",5,25,300,"Cuisine"),
    (5,"Materiel nettoyage","EH","Tampon a recurer","paquet",4,20,500,"Cuisine"),
    (5,"Materiel nettoyage","EH","Brosse","piece",2,10,1000,"Menage"),
    (5,"Materiel nettoyage","EH","Serpilliere","piece",3,15,800,"Menage"),
    (5,"Materiel nettoyage","EH","Balai","piece",2,10,1500,"Menage"),
    (5,"Hygiene","EH","Gants menagers","paire",4,20,500,"Menage"),
    (5,"Hygiene","EH","Gants jetables","boite",4,20,2000,"Cuisine"),
    (5,"Hygiene","EH","Gel hydroalcoolique","bouteille",3,15,1500,"Salle"),
    (5,"Hygiene","EH","Papier toilette","paquet",6,30,500,"Menage"),
    (5,"Hygiene","EH","Sac poubelle","rouleau",6,30,800,"Menage"),
    (5,"Hygiene","EH","Insecticide","aerosol",2,10,2000,"Menage"),
    # ===== 6: CONSOMMABLES ADMINISTRATIFS =====
    (6,"Papeterie","CA","Fiches de stock","bloc",2,10,500,"Bureau"),
    (6,"Papeterie","CA","Cahiers de stock","piece",2,10,300,"Bureau"),
    (6,"Papeterie","CA","Stylos","boite",2,10,1500,"Bureau"),
    (6,"Papeterie","CA","Marqueurs","boite",2,10,1000,"Bureau"),
    (6,"Papeterie","CA","Classeurs","piece",2,10,800,"Bureau"),
    (6,"Papeterie","CA","Feuilles A4","rame",2,10,2500,"Bureau"),
    (6,"Papeterie","CA","Etiquettes autocollantes","paquet",2,10,1000,"Bureau"),
    (6,"Impression","CA","Encre imprimante","cartouche",2,8,5000,"Bureau"),
    (6,"Impression","CA","Registres","piece",2,10,1500,"Bureau"),
    # ===== 7: EVENEMENTS ET SERVICE TRAITEUR =====
    (7,"Decorations","EV","Nappes jetables","paquet",4,20,1500,"Reserve B"),
    (7,"Decorations","EV","Sets de table","paquet",4,20,1000,"Reserve B"),
    (7,"Decorations","EV","Bougies","boite",3,15,500,"Reserve B"),
    (7,"Decorations","EV","Decorations de table","lot",2,10,2000,"Reserve B"),
    (7,"Vaisselle evenementielle","EV","Gobelets evenementiels","paquet",4,20,800,"Reserve B"),
    (7,"Vaisselle evenementielle","EV","Assiettes evenementielles","paquet",4,20,1200,"Reserve B"),
    (7,"Vaisselle evenementielle","EV","Couverts evenementiels","paquet",4,20,800,"Reserve B"),
    (7,"Materiel service","EV","Glacieres de service","piece",1,5,15000,"Reserve B"),
    (7,"Materiel service","EV","Seaux a glace","piece",2,10,3000,"Bar"),
    # ===== 8: ESPACE JEUX =====
    (8,"Acces et tickets","EJ","Jetons de jeu","lot",2,10,5000,"Jeux"),
    (8,"Acces et tickets","EJ","Bracelets d'acces","paquet",3,15,2000,"Jeux"),
    (8,"Acces et tickets","EJ","Tickets d'acces","rouleau",3,15,1500,"Jeux"),
    (8,"Electricite","EJ","Piles AA","paquet",4,20,1500,"Jeux"),
    (8,"Electricite","EJ","Piles AAA","paquet",4,20,1500,"Jeux"),
    (8,"Electricite","EJ","Multiprises","piece",2,5,3000,"Jeux"),
    (8,"Electricite","EJ","Rallonges electriques","piece",2,5,2500,"Jeux"),
    (8,"Entretien jeux","EJ","Lingettes de nettoyage","paquet",4,20,1000,"Jeux"),
    (8,"Entretien jeux","EJ","Spray nettoyant ecrans","bouteille",2,10,2000,"Jeux"),
]
